export const ADD_PRODUCT = "ADD_PRODUCT";
export const REMOVE_PRODUCT = "REMOVE_PRODUCT";
export const PRE_ADD_PRODUCT = "PRE_ADD_PRODUCT";
export const PRE_REMOVE_PRODUCT = "PRE_REMOVE_PRODUCT";
export const PRE_REPLACE_PRODUCT = "PRE_REPLACE_PRODUCT";
